![PYTHON](https://github.com/Chilangdon20/PYTHON/blob/master/Curso%20Basico/CursoExpress/Imagenes/Logo.png?raw=true)

# ¿Cómo escribir código eficiente usando Python?

## Introducción:

En esta sección aprenderemos cómo escribr código más limpio,más rápido y mas eficiente en Python.Aprenderemos cómo encontrar posibles cuellos de botella en nuestro código, tambien veremos la importancia de los malos patrones de diseño , utilizando las bibliotecas estándar de Python,Numpy & Pandas.

## ¿Que se entiende por código eficiente en Python?

Nos refermios a **eficiente** como palabra clave que satisface dos conceptos clave:

 * "El código eficiente es rápido y tiene una pequeña latencia entre la ejecución y la devolución de un resultado." , en otras palabras es **el tiempo minimo de compilación.**

 * "El código eficiente asigna recursos con habilidad y no esta sijeto a una sobrecarga innecesaria.", en otras palabras es el **tiempo minimo de consumo.**

La definición de tiempo de ejecución rápido y uso de memotia pequeña depende de la tarea que esteos realizando.

Escribir código Python de la manera que fue diseñado a menudo se conoce como código **Pythonic**, esto significa que el código que se escribe sigue las mejores prácticas y principios rectores de Python.

El codigo Pythonic tiene a ser menos detallado y mas fácil de intepretar, aqui veremos un ejemplo a continuación:




In [ ]:
# Cdigo No.Pythonic
num_triples = []


for i in range(len(numeros)):
  num_triples.append(numeros[i] * 2)

# Código Pythonic
num_triples = [y * 2 for i in numeros]

Podemos observar que el código normal o No.pythonic es mucho mas detallado y tarda mucho mas tiempo en ejecutarse.

Para que nosotros podamos ver cuales son los principios o modismos que se usan en Pythonic podemos escribir el siguiente código:

In [3]:
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!


Esta es una lista de algunos modismos y mejores practicas que resumen la filosofía de diseño de Python.

### Ejemplo:

Supongamos que estamos buscando coleccionar los nombres de ciertas personas cuya longuitud es mayor o igual a 8.El enfoque típico es crear una variable de índice (i), usar i para iterar sobre la lista y usar una instrucción if para recopilar los nombres con 5 letras o más:

In [20]:
nombres = ["Diego","Lomachenko","Vinc","Fermin","Mariana"]
i = 0
lista = []
while i < len(nombres):
    if len(nombres[i]) >= 5:
        lista.append(nombres[i])
    i += 1
print(lista)

['Diego', 'Lomachenko', 'Fermin', 'Mariana']


Un enfoque más pythonic recorrería el contenido de los nombres, en lugar de utilizar una variable de índice. Imprime mejor_lista.

In [21]:
mejor_lista = []
for nombre in nombres:
  if len(nombre) >= 5:
     mejor_lista.append(nombre)
print(mejor_lista)

['Diego', 'Lomachenko', 'Fermin', 'Mariana']


Pero aun podemos mejorar mas el codigo :

In [22]:
super_lista = [nom for nom in nombres if len(nombres) >= 5]
print(super_lista)

['Diego', 'Lomachenko', 'Vinc', 'Fermin', 'Mariana']


Python nos brinda ciertas herramientas integradas para poder simplificar nuestro codigo y escribirlo mucho mas eficiente, cabe mencionar que los componentes integrados se denominan **Python Standard Library**.

Esta biblioteca viene en cada versión de python y es una de las mayores fortalezas de Python.Python tiene varios tipos de datos incroporados , nos centraremos en tipos de datos como listas, tuplas, conjuntos & diccionarios.

Python tambien brinda funciones integradas que proporcionan una variedad de características de resolución de problemas como son ``print()``,``len()``,``range()``,``round()``,``enumerate()``,``map()``,``zip()`` entre otras.

## Función ``range()``


Esta es una herramienta muy util cuando queremos crear secuencias de números,supongamos que queremos crear una lista de numeros enteros del 5 al 20:


In [24]:
num = [5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
num

[5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

Podriamos hacer lo anterior pero no es muy eficiente, en su lugar usaremos ``range()``, podemos proporcionarle un rango con un valor inicial y final para crear nuestra secuecniade números

In [27]:
# range(valor_inicial,valor_final)
num = range(5,21)

lista_num = list(num)
print(lista_num)

[5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]


O bien , podemos proporcionar un solo valor como argumento suponiendo que queremos que nuestra secuencia comience en cero.

In [31]:
# range(valor_final)
numeros = range(21)

lista_numeros = list(numeros)
print(lista_numeros)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]


Tengamos en cuenta que el valor de detención es exclusivo, o bien hasta ,pero sin incluir el valor.

Tambien tengamos en cuenta que la función ``range()``devuelve un objeto de tipo rango, que podemos convertir a una lista e imprimir.

La función range tambien puede aceptar un valor de inicio, final y paso.

In [33]:
nuevos_numeros = range(1,21,3)
numeros_lista = list(nuevos_numeros)
print(numeros_lista) 

[1, 4, 7, 10, 13, 16, 19]


En esta sección de código le decimos a python que queremos crear una secuencia de nueros que comienzan en 1 y teminan en 20 y se incrementan en tres.


## Función ``enumerate()``

La función ``enumerate()``crea un par de elementos de índice para cada elemento en el objeto proporcionado,por ejemplo llamar a enumerate en las letras de una lista produce una secuencia de valores indexados,similar a la funcion ``range()``devuelve un objeto enumerate que tambien se puede convertir en una lista e imprimirveamos un ejemplo:

In [35]:
letras = ['S','P','R','C','J']
letras_indexadas = enumerate(letras)

lista_indexada_letras = list(letras_indexadas)
print(lista_indexada_letras)

[(0, 'S'), (1, 'P'), (2, 'R'), (3, 'C'), (4, 'J')]


También podemos especificar el índice inicial de enumerate con el argumento de la palabra clave ``start``,veamos un ejemplo.

In [36]:
letras_indexadas2 = enumerate(letras,start=4)
lista_indexada2_letras = list(letras_indexadas2)
print(lista_indexada2_letras)

[(4, 'S'), (5, 'P'), (6, 'R'), (7, 'C'), (8, 'J')]


En el codgio anterior le decimos a la función enumerate que comiende el índice a las cuatro pasando el parametro start igual a cuatro.



## Función ``map()``

La función ``map()``aplica una función a cada elmento de un objeto,a continuación veamos que la funcion map recibe 2 argumetnos , primero la funcion a aplicar y segundo el objeto donde aplicamos la funcion.



In [41]:
costos = [12.56,32.4,56,8.2,23.5,7.2]
costos_redond = map(round,costos)
print(list(costos_redond))

[13, 32, 56, 8, 24, 7]


Tengamos en cuenta que también podemos utilizar map con una función lambda como parametro, veamos un ejemplo:

In [42]:
nums = [2,5,7,9,0]
nums_elevados = map(lambda x: x**2,nums)
print(list(nums_elevados))

[4, 25, 49, 81, 0]


# El poder de NumPy

## Introdución:

Numpy es un paquete invaluable de Python para los cientificos de datos,es el paquete fundamental para la informática científica en Python y proporciona una serie de beneficios para escribir código eficiente, a continuacion veremos una de las ventajas más importantes de NumPy, la matriz de NumPy.



In [46]:
num_lista = list(range(5))
num_lista

[0, 1, 2, 3, 4]

La matriz de NumPy proporciona una alternativa rápida y eficiente en memoria a las listas de Python.

Por lo general importamos NumPy como no y usamos la matriz de puntos no para crear una matriz NumPy,estas son homogeneas lo que significa que deben de contener elenentos del mismo tipo.

In [48]:
import numpy as np

nums_np = np.array(range(5))
nums_np

array([0, 1, 2, 3, 4])

Las matrices en NumPy son homogéneas , lo que significa que deben contener elementos del mismo tipo, a continuación un ejemplo.

In [49]:
# Matriz NumPy Homogenea
num_np_hom = np.array([7,8,9])
num_np_hom


array([7, 8, 9])

Podemos ver el tipo de cada elemento usando el método ``.dtype```


In [50]:
num_np_hom.dtype

dtype('int64')

Supongamos que creamos una matriz usando difrentes tipos de datos:

In [52]:
nums_no_float = np.array([5,6.78,7])
nums_no_float

array([5.  , 6.78, 7.  ])

Podemos observar que numpy convirtió los enteros en flotantes para retener la naturaleza homogénea de esa matriz, ahora verificaremos el tipo de dato de la matriz.

In [53]:
nums_no_float.dtype

dtype('float64')

## Funcionalidad de transmisión de Matrices de NumPy.

Al analizr nuestros datos, a menudo realizaremos operaciones en colecciones completas de valores rapidamente.Digamos por ejemplo que queremos elevar al cuadrado cada número de una lista de números, seria bueno si solamente pudieramos aplicar la operacion a la lista de valores, desafortunadamente las listas de Python no admiten este tipo de cálculos.

In [54]:
nums = [-3,-2,-1,0,1,2,3]
nums ** 2

TypeError: ignored

Podriamos elevar al cuadrado usando un bucle for o usando una compresion de la lista.

In [55]:
#Forma infeciciente 
nums_cuadrados = []
for num in nums:
  nums_cuadrados.append(num ** 2)
print(nums_cuadrados)

[9, 4, 1, 0, 1, 4, 9]


In [56]:
# Mejor opción pero no la mejor
nums_cuadrados = [num ** 2 for num in nums]
print(nums_cuadrados)

[9, 4, 1, 0, 1, 4, 9]


Ninguno de los enfoques anteriores es adecuado y eficiente,aqui radica la segunda ventaja de los arreglos numpy, la **funcionalidad de transmisión.**

Las matrices NumPy vectorizan las operaciones , por lo que se realizan en todos los elementos de un objeto a la vez, esto nos permite realizar cálculos de manera mas eficiente en matrices enteras.

In [57]:
nums_np = np.array([1,2,3])
nums_np ** 3

array([ 1,  8, 27])

Otra ventaja de los arreglos NumPy es su capacidad de indexación, a continuación compararemos la indexación basica entre una matriz unidimensional y una lista .

In [58]:
# Indexado 1-D basico(listas)
nums = [-3,-1,0,1,3]
nums[2]


0

In [59]:
# Indexado 1-D basico(Matriz)
nums_np = np.array(nums)
nums_np[2]

0

In [60]:
# Indexado 1-D basico(listas)
nums[-1]

3

In [61]:
# Indexado 1-D basico(Matriz)
nums_np[-1]

3

Al compara la indexación basica entre una matriz unidimensional y una lista , las capacidades son idénticas.Cuando se usan matrices y listas bidimensionales, las ventajas de las matrices son claras, veamos a continuacion un ejemplo.

In [62]:
# 2-D lista
nums2 = [[1,2,3],
         [4,5,6]]
#2-D matriz
nums2_np = np.array(nums2)


Para devolver el segundo elemento de la primera fila en nuestras variables veremos notablemente las diferencias:

In [63]:
# Indexado Bsico 2-D(listas)
nums2[0][1]

2

In [64]:
# Indexado Basico 2-D(matrices)
nums2_np[0,1]

2

Podemos observar que la sintaxis de la lista es un poco mas detallada ya que tenemos que poner tanto el cero como el uno en diferentes corchetes mientras que en la matriz no.

### OBSERVACIÓN:

Para devolver la primera columna de valores de nuestros objetos , la sintaxis de la matriz es mucho mas simple, veamos a continuación.

In [65]:
#Lista
[col[0] for col in nums2]

[1, 4]

In [66]:
#Matriz
nums2_np[:,0]

array([1, 4])

Las matrices NumPy tambien tienen una técnica especial llamada indexación booleana,supongamos que deseamos reunir solo números postivos de la secuencia siguiente:

In [69]:
nums = [-2,-6,-3,8,90,43]
nums_np = np.array(nums)

Con una matriz , podemos crear una máscara booleana usando una simple desigualdad.

In [72]:
nums_np > 0

array([False, False, False,  True,  True,  True])

La indexación de la matriz es tan simple como encerrar esta desgiauldad entre corchetes.

In [73]:
nums_np[nums_np> 0]

array([ 8, 90, 43])

Para hacer esto en una lista,necesitamos escribir un bucle for para filtrar la lista o usar una comprension en la lista:

In [74]:
# Forma ineficiente
pos = []
for num in nums:
  if num > 0:
    pos.append(num)
print(pos)

[8, 90, 43]


In [75]:
# Mejor forma pero ineficiente aun
pos = [num for num in nums if num > 0]
print(pos)

[8, 90, 43]
