![texto alternativo](https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse3.mm.bing.net%2Fth%3Fid%3DOIP.YjG7QZ-zNBAbVT13iCm5QwHaEJ%26pid%3DApi&f=1)

[recurso](https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse3.mm.bing.net%2Fth%3Fid%3DOIP.YjG7QZ-zNBAbVT13iCm5QwHaEJ%26pid%3DApi&f=1)
# Introducción A Las entrañas De NumPy.

## Introducción:

Ahora que hemos aprendido lo más basico de POO, hablemos de NumPy la biblioteca que esta detras de las bibliotecas que usamos diario como Pandas.

NumPy es un paquete para computación cientifica en Python que incluye la capacidad de hacer álgebra Lineal NumPy fue creado por que muchas operaciones de computación científica estan basadas es una estructura matemática , como las matrices bien conocidas en NumPy como arrays.

Las matrices son esencialmente datos agrupados por filas y columnas en ciencia de Datos , usamos NumPy para cuando analisamos datos y amenudo deben presentarse como una matriz o una tabla de bases de datos.


Por ejemplo , creamos matrices al crear conjuntos de datos de entrada para modelizar, al realizar un análisis agregado o al crear matrices de a1lgebra lineal como cálculos en algoritmos de recomendación.


Los fundamentos de NumPy se usan para construir todas las bibliotecas que usamos a diario.La documentación de pandas muestra que los objetos de la serie de pandas,que componen DataFrame son un ``ndarray``.

Recordemos que un ``ndarray``es otro nombre para una Matrix NumPy.Pensemos en las matrices NumPy como formas similares en estructuras y forma a las listas en Python.

![recurso](https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.du3D14Cyxq8-z1-6jDcA1QHaBw%26pid%3DApi&f=1)


[recurso](https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.du3D14Cyxq8-z1-6jDcA1QHaBw%26pid%3DApi&f=1)

A diferencia de las listas, las matrices NumPy pueden ser "n- dimensionales", por lo que mas de una dimensión , llamada ``numpy.array``o ``ndarray`` y solo toman un tipo de datos como una cadena o un entero a la vez.

La imagen anterior muestra varios ejemplos de matrices junto con sus dimensiones, comenzando en el tamaño de la izquierda , puedes ver que la matriz *1D* .. Si asi como One Direction, se parece más a una lista.

Una vez que tienes una matriz *2D* en el medio, tiene varios ejes.Una matriz *3D* se vuelve un poco mas compleja en este curso solo trataremos con matrices 1 y 2D.

Para crear una matriz , importamos NumPy como np para que podamos usar el método de matriz en la primera fila.

Ejemplo:



In [1]:
import numpy as np

En la segunda linea , creamos una matriz de una dimension , que incluye los miembros 5,6,7.

In [2]:
np_array = np.array([5,6,7])

En la tercera linea , podemos imprimir la matriz y vemos que devolvemos un objeto de matriz.

In [3]:
print(np_array)

[5 6 7]


Si vemos el tipo de nuestra amtriz , podemos ver que ahora es una matriz NumPy!

In [4]:
print(type(np_array))

<class 'numpy.ndarray'>


El ejemplo anterior fue muy simple, pero las matrices NumPy pueden tener todas las formas y tamaños.

El elemento clave es el eje , que es otro nombre para la fila o columna el eje en cero se refiele a las filas y el eje en uno a las columnas.

In [ ]:
array([0,1,2,3,4],
      [4,5,6,7,8],
      [10,11,12,13,14])

Entonces el ejemplo de aqui arriba tiene tres elementos a lo largo del eje 0.

In [ ]:
array([7,8,9])

Mientras que este de aqui arriba tiene un elemento a lo largo del eje 0.Cada eje tiene un número dado de elementos , entonces el primer ejemplo tiene 5 elementos , mientras que el ejemplo 2 tiene 3 elementos, hay muchos mas elementos , pero lo mantendremos simple para realmente llegar al corazo1n.